mysite/myapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
     path('',views.index),
     path('products/',views.products,name='products'),
     path('products/<int:id>/',views.product_detail,name='product_detail'),
     path('products/add/',views.add_product, name='add_product'),
     path('products/update/<int:id>/',views.update_product, name='update_product'),
     path('products/delete/<int:id>/',views.delete_product, name='delete_product'),
]     
     
    
    
    

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls')), 
    path('users/',include('users.urls')),   
  
]

urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.contrib import admin
from django.urls import path
from .import views
from django.contrib.auth import views as authentication_views

app_name = 'users'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',views.profile,name='profile'),

]     
     
    
    
    

mysite/myapp/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    desc = models.CharField(max_length=200)
    image = models.ImageField(blank=True,upload_to='images')   
    
    

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile.jpg',upload_to='profile_pictures')
    contact_number = models.CharField(max_length=100,default="999")
     

mysite/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True,widget=forms.EmailInput(attrs={'class':'form-control'}))
    username = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'form-control'}))
    password1 = forms.CharField(required=True,widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(required=True,widget=forms.PasswordInput(attrs={'class':'form-control'}))
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.username = self.cleaned_data['username']
        user.password1 = self.cleaned_data['password1']
        user.password2 = self.cleaned_data['password2']
        if commit:
            user.save()
        return user

mysite/myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Product
# Create your views here.
def index(request):
    return HttpResponse("Hello, world! You're at the polls index.") 

def products(request):
    products = Product.objects.all()
    context ={
        'products':products
    }
    return render(request, 'myapp/index.html', context)

def product_detail(request, id):
    product = Product.objects.get(id=id)
    context={
        'product':product
    }
    return render(request, 'myapp/detail.html', context)

def add_product(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        price = request.POST.get('price')
        desc = request.POST.get('desc')
        image = request.FILES.get('upload', None)
        product = Product(name=name, price=price, desc=desc, image=image)
        product.save()
    return render(request, 'myapp/addproduct.html')

def update_product(request, id):
    product = Product.objects.get(id=id)
    if request.method == 'POST':
        product.name = request.POST.get('name')
        product.price = request.POST.get('price')
        product.desc = request.POST.get('desc')
        product.image = request.FILES.get('upload', None)
        product.save()
        return redirect('/myapp/products')
        
    context ={
        'product': product
    }
    return render(request, 'myapp/updateproduct.html', context)

def delete_product(request, id):
    product = Product.objects.get(id=id)
    context={
        "product":product,
    }
    if request.method == 'POST':
        product.delete()
        return redirect('/myapp/products')
    return render(request, 'myapp/delete.html', context)

mysite/users/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('myapp/products')
        
    form = NewUserForm()
    context={
        'form':form,
    }
    return render(request, 'users/register.html', context)

@login_required
def profile(request):
    return render(request, 'myapp/profile.html')

mysite/myapp/templates/myapp/addproduct.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl font-bold m-10">➕Add Product</h1>
<form class="w-1/2 bg-white shadow-md m-10 px-8 py-8" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Product Name</label>     
        <input class="shadow appearance-none border rounded py-2 px-3 text-gray-700" placeholder="name" value={{product.name}} type="text" name="name" id="name" required>
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="price">Product Price</label>     
        <input class="shadow appearance-none border rounded py-2 px-3 text-gray-700" placeholder="price" type="number" valu={{product.price}} name="price" id="price" required>
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="desc">Product Description</label>     
        <textarea class="shadow appearance-none border rounded py-2 px-3 text-gray-700" placeholder="desc" name="desc" value={{product.desc}} id="desc" required rows="3"></textarea>
    </div>
    <div class="mb-4">
        <img src="{{product.image.url}}" alt="">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="upload">Product Image</label>     
        <input class="py-2" type="file" accept="image/*" name="upload" id="upload" required>
    </div>
    <div class="mb-4">
        <input class="bg-green-500 text-white px-5 py-2 rounded-full" type="submit" value="Add Product">
    </div>
</form>
{% endblock %}

mysite/myapp/templates/myapp/base.html
{% load static %}

<html>
    <head>
        <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
    </head>
    <body>
        <nav class="bg-white shadow-lg">
            <div class="max-w-6xl mx-auto px-4">
                <div class="flex justify-between">
                    <div class="flex space-x-7">
                        <div>
                            <a href="#" class = "flex items-center px-2 py-4">
                            <img class="h-8 w-8" src="{% static 'myapp/images/shopping.png' %}"alt="">
                            <span class="text-gray-500 font-semibold text-lg" >Buy & Sell</span>    
                            </a>
                        </div>
                        <div class="items-center flex space-x-1">
                          <a href="#" class="py-4 px-2 text-gray-500 font-semibold border-b-4 border-green-500">Home</a> 
                          <a href="#" class="py-4 px-2 text-gray-500 font-semibold">About</a> 
                          <a href="#" class="py-4 px-2 text-gray-500 font-semibold">Contact</a> 

                          {% if user.is_authenticated %}
                            <a class="py-4 px-40 text-gray-500 font-semibold" href="{% url 'users:logout'%}">Logout</a>
                            <a class="py-4 px-40 text-gray-500 font-semibold" href="{% url 'users:profile'%}">Profile</a>

                          {% else %}
                            <a class="py-4 px-40 text-gray-500 font-semibold" href="{% url 'users:login'%}">Login</a>
                        
                          {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
    </body>
</html>

mysite/myapp/templates/myapp/delete.html
{% extends 'myapp/base.html'%}
{% block content %}
    <h1 class='text-2xl m-10 font-bold'>Delete Product</h1>
    <form method="post" class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8">
        {% csrf_token %}
        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2">Are you sure you want to delete this product?</label>
        </div>
        <div>
            <label class="block text-gray-700 text-sm font-bold mb-2">Product Name: {{ product.name }}</label>
        </div>
        <div class="mb-4">
            <img src="{{ product.image.url }}" alt="{{ product.name }}">
        </div>
        <input class="bg-red-500 text-white px-5 py-2" type="submit" value="Confirm">

        <a href="{% url 'products' %}" class="bg-blue-500 text-white px-5 py-2 rounded-full">Cancel</a>
    </form>
{% endblock %}

mysite/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block content %}

<div class="flex p-10 w-full h-200">
    <img class="w-1/3" src="{{product.image.url}}" alt="">
    <div class="w-2/3 text-xl ml-10 mt-10">
        <div class="mt-5">{{product.name}}</div>
        <div class="mt-5 text-green-500">$ {{product.price}}</div>
        <div class="mt-5 text-gray-700">{{product.desc}}</div>
    </div>
</div>

{% endblock %}

mysite/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block content %}
<!-- Site hero starts here-->
<main class="mt-10 mx-auto max-w-7xl px-4 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28 bg-gray-100">
    <div class="sm:text-center lg:text-left">
        <h1 class="text-4xl font-extrabold text-indigo-700 sm:text-5xl md:text-6xl">
            <span class="block xl:inline"> Premium Products </span>
            <span class="block text-green-500 xl:inline"> Non-premium Prices</span>
        </h1>
        <p class="mt-3 text-base text-gray-600 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Get the best quality products across the globe</p>
    </div>
</main>
<!-- Site hero ends here-->

<div class="flex mt-5 p-10 justify-center bg-gray-100">
    <h1 class="text-3xl font-normal text-gray-600 sm:text-4xl md:text-5xl text-center"> Recent Products </h1>    
</div>
<div class="p-10 bg-white">
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-5">
        {% for product in products %}
            <a href="{% url 'product_detail' product.id %}" class="card-link">
                <div class="card rounded overflow-hidden shadow-lg">
                    {% if product.image %}
                    <img class="card-image" src="{{product.image.url}}" alt="{{product.name}}">
                    {% endif %}
                    <div class="card-content px-6 py-4">
                        <div class="card-title text-xl font-bold mb-2 text-indigo-700">{{product.name}}</div>
                        <div class="card-price text-xl font-bold text-teal-500 mb-2">$ {{product.price}}</div>
                        <p class="card-desc text-gray-600">{{product.desc}}</p>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

mysite/myapp/templates/myapp/updateproduct.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl font-bold m-10">➕Update Product</h1>
<form class="w-1/2 bg-white shadow-md m-10 px-8 py-8" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Product Name</label>     
        <input class="shadow appearance-none border rounded py-2 px-3 text-gray-700" placeholder="name" type="text" name="name" id="name" required>
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="price">Product Price</label>     
        <input class="shadow appearance-none border rounded py-2 px-3 text-gray-700" placeholder="price" type="number" name="price" id="price" required>
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="desc">Product Description</label>     
        <textarea class="shadow appearance-none border rounded py-2 px-3 text-gray-700" placeholder="desc" name="desc" id="desc" required rows="3"></textarea>
    </div>
    <div class="mb-4">
        <img class="w-20 h-20" src="{{ product.image.url }}" alt="">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="upload">Product Image</label>     
        <input class="py-2" type="file" accept="image/*" name="upload" id="upload" required>
    </div>
    <div class="mb-4">
        <input class="bg-green-500 text-white px-5 py-2 rounded-full" type="submit" value="Update Product">
    </div>
</form>
{% endblock %}

mysite/users/templates/users/login.html
{% extends 'myapp/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    
<h1 class="text-2xl m-10 font-bold text-center">
    <i class="fas fa-user-plus fa-2x mr-2"></i> Login User
</h1>
<div class="container py-5">
    <form class="bg-white p-10 shadow-lg rounded" method="post"> 
        {% csrf_token %}
        <div class="form-group mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="username">Username</label>
            <input type="text" class="form-control bg-gray-200 text-gray-700 p-2 rounded" id="username" name="username" placeholder="Enter username">
        </div>
        
        <div class="form-group mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="password">Password</label>
            <input type="password" class="form-control bg-gray-200 text-gray-700 p-2 rounded" id="password" name="password" placeholder="Enter password">
        </div>
      
        <button type="submit" class="btn btn-primary bg-indigo-500 text-white p-2 rounded">Login</button>
    
    </form>
</div>
{% endblock %}
{{ form }}

mysite/users/templates/users/logout.html
{% extends 'myapp/base.html'%}
{% block content %}
<h1> You have been logged out </h1>
{% endblock %}

mysite/users/templates/users/profile.html
{% extends 'myapp/base.html'%}
{% block content %}
    <h1>This is a profile page</h1>
    <h1>{{user.username}}</h1>
{% endblock %}

mysite/users/templates/users/register.html
{% extends 'myapp/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    
<h1 class="text-2xl m-10 font-bold text-center">
    <i class="fas fa-user-plus fa-2x mr-2"></i> Register User
</h1>
<div class="container py-5">
    <form class="bg-white p-10 shadow-lg rounded" method="post"> 
        {% csrf_token %}
        <div class="form-group mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="username">Username</label>
            <input type="text" class="form-control bg-gray-200 text-gray-700 p-2 rounded" id="username" name="username" placeholder="Enter username">
        </div>
        <div class="form-group mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="email">Email</label>
            <input type="text" class="form-control bg-gray-200 text-gray-700 p-2 rounded" id="email" name="email" placeholder="Enter email">
        </div>
        <div class="form-group mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="password">Password</label>
            <input type="password" class="form-control bg-gray-200 text-gray-700 p-2 rounded" id="password" name="password" placeholder="Enter password">
        </div>
        <div class="form-group mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="confirm_password">Confirm Password</label>
            <input type="password" class="form-control bg-gray-200 text-gray-700 p-2 rounded" id="confirm_password" name="confirm_password" placeholder="Confirm password">
        </div>
        <button type="submit" class="btn btn-primary bg-indigo-500 text-white p-2 rounded">Register</button>
    
    </form>
</div>
{% endblock %}
{{ form }}